
[package]
name = "dl"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]
bench = false

[build-dependencies]
cc = "1.2.34"

[dependencies]
uuid = "1.3.2"
num-traits = "0.2.19"
co5_backflow_public = { path = "../co5_client"}
rand = "0.9.2"
